### ISSUE TITLE
Dead links in README.md

### ISSUE THREAD

**Issue by ghost** [interledger/tutorials#16]

**Comment by adrianhopebailie** [comment]
This is a symptom of everything under `https://interledger.org/tutorials` rendering from a different repo to the main site.

The base url for everything is `https://interledger.org` so relative URLs in the `tutorials` repo either work on Github or when rendered. (Same issue we had with publishing the RFCs).

I propose that we leave this broken on Github for now (we want people browsing the tutorials online) and consider migrating to an explicit publishing process like we have for the RFCs later. This can perform a URL find/replace like the publish script does for the RFCs so they work on Github and are fixed to work online before publishing.

**Comment by michielbdejong** [comment]
But this is about the readme of the repo, which is different from the index.md which gets rendered, right?
