### ISSUE TITLE
improve flow of argument for http-ilp

### ISSUE THREAD

**Issue by michielbdejong** [interledger/tutorials#19]
The bonus part of the Letter Shop tutorial introduces a competing `Pay` header, we should make it use PSK. We should also move it into the http-ilp tutorial and make that the second one. And instead of a proxy, it should be a command-line script. Its advantage is that it avoids cut-and-paste between script and browser. Then switching to koa-ilp and switching to ilp-curl can be done in two steps, each explained for their merit.

After that, the streaming payments tutorial no longer needs to explain PSK, just that this is an alternative flow, with mid-request payment.

**Comment by adrianhopebailie** [comment]
This presumes that PSK is the only way to do HTTP ILP.

I am still in favour of a header format that allows the transport layer protocol to be specified so that appropriate protocols can be used for different use cases.

See https://github.com/interledger/rfcs/issues/325

I think we need to resolve that isse first and then come back to the tutorials to ensure they reflect the current consensus

**Comment by michielbdejong** [comment]
Right. There are many ways to word a payment request, and the fact that there is no standard yet for how to write down a machine-readable payment request, is probably not a coincidence. Let's see what features we want to support:

* describe, in a `Pay` header on a 200 or 402 response, in which way(s) the client can complete the required payment for the entire resource that was requested.
* describe, in a `Pay` header on a  200 response, in which way(s) the client can complete the required payment per chunk of the resource that was requested (e.g. price per byte).
* In case of 402, the request needs to be reinitiated, and some sort of "session token" needs to be presented in the second request.
* In case of 200, there can be a problem where a paid request fails - how would you repeat the request for the resource for which you already paid? you would still need some sort of cookie.
* prepaid balance which you buy once, and then use for many requests. this is useful if transaction fees are high.

**Comment by michielbdejong** [comment]
l'll use the format proposed in https://datatracker.ietf.org/doc/draft-hope-bailie-http-payments/?include_text=1 with payment-method-identifier 'interledger-psk' for PSK, and 'interledger-condition' for condition.

**Comment by adrianhopebailie** [comment]
Let's discuss this on interledger/rfcs#325

Updating the tutorial is orthogonal to figuring out the standard

**Comment by adrianhopebailie** [comment]
Closed in favour of #27
